### ISSUE TITLE
Define null OAuthData

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/ide-login#15]
OAuthDataStore contract relies on having loadOAuthData returning an object with `null` fields in case no persisted one exists:

https://github.com/GoogleCloudPlatform/ide-login/blob/master/src/main/java/com/google/cloud/tools/ide/login/OAuthDataStore.java#L37

It'd be a better interface to have OAuthData define a constant for the `null` OAuthData instance and use that in comparisons.

**Comment by chanseokoh** [comment]
Not relevant anymore. It's returning a `Set`.
